### ISSUE TITLE
napari widget Image shift controls does not work properly

### ISSUE THREAD

**Issue by ondrejstranik** [kasasxav/ImSwitch#163]
**Bug description**
error message issued when arrows buttons in the napari widget are pressed:
```
ERROR [ExceptionHandler] Traceback (most recent call last):
  File "C:\Users\ostranik\Documents\GitHub\ImSwitch\imswitch\imcommon\view\guitools\naparitools.py", line 265, in _on_up
    self._do_shift(0, -self._get_shift_distance())
  File "C:\Users\ostranik\Documents\GitHub\ImSwitch\imswitch\imcommon\view\guitools\naparitools.py", line 281, in _do_shift
    for layer in self.viewer.layers.selected:
AttributeError: 'LayerList' object has no attribute 'selected'
```
**Correction**

change in the source naparitools.py methods `on_reset(self)` and `_do_shift(self)`: 

`self.viewer.layers.selected` --> `self.viewer.layers.selection`

**Comment by kasasxav** [comment]
@ondrejstranik thank you! Would you want to open a PR with the changes?
